CREATE TABLE "GBG_5049_COND_MAINT"(
 "CONDITION_ID" IDENTITY DEFAULT '0',
 "CONDITION_NAME" LONGVARCHAR NOT NULL ,
 "CONDITION_QUERY" LONGVARCHAR NOT NULL ,
 "HOLD_NOTIFICATIONS" BIT NOT NULL ,
 "HOOK_NUMBER" LONGVARCHAR,
 UNIQUE ("CONDITION_ID"));
